"""
Django settings for cashoclock project.

Generated by 'django-admin startproject' using Django 1.8.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=&uhfsemn0h$&=#&=tw7(e-fenf9)jq^_oo(5oh@wxto+^jtl%'

# SECURITY WARNING: don't run with debug turned on in production!
os.environ.setdefault("CASHOCLOCK_DEBUG", "True")
DEBUG = str(os.environ["CASHOCLOCK_DEBUG"]) == "True"

ALLOWED_HOSTS = ['*']

LOGIN_URL = '/accounts/login'
LOGOUT_URL = '/accounts/logout'
LOGIN_REDIRECT_URL = '/'
MIN_PASSWORD_LENGTH = 6

LOCALE_PATHS = (
  os.path.join(BASE_DIR, 'locales'),
)

# Application definition
INSTALLED_APPS = (
  'django.contrib.auth',
  'django.contrib.contenttypes',
  'django.contrib.sessions',
  'django.contrib.messages',
  'django.contrib.staticfiles',
  'django.contrib.humanize',
  'django.contrib.admin',
  'debug_toolbar',
  'widget_tweaks',
  'braces',
  'hashids',
  'common',
  'finance',
)


MIDDLEWARE_CLASSES = (
  'django.contrib.sessions.middleware.SessionMiddleware',
  'django.middleware.common.CommonMiddleware',
  'django.middleware.csrf.CsrfViewMiddleware',
  'django.contrib.auth.middleware.AuthenticationMiddleware',
  'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
  'django.contrib.messages.middleware.MessageMiddleware',
  'django.middleware.clickjacking.XFrameOptionsMiddleware',
  'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'cashoclock.urls'

TEMPLATES = [
  {
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [],
    'APP_DIRS': True,
    'OPTIONS': {
      'context_processors': [
        'django.template.context_processors.debug',
        'django.template.context_processors.request',
        'django.contrib.auth.context_processors.auth',
        'django.contrib.messages.context_processors.messages',
      ],
    },
  },
]

WSGI_APPLICATION = 'cashoclock.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

os.environ.setdefault("CASHOCLOCK_DB_NAME", "cashoclock")
os.environ.setdefault("CASHOCLOCK_DB_USER", "cashoclock")
os.environ.setdefault("CASHOCLOCK_DB_PASS", "cashoclock")
os.environ.setdefault("CASHOCLOCK_DB_HOST", "localhost")

DATABASES = {
  'default': {
    'ENGINE': 'django.db.backends.postgresql_psycopg2',
    'NAME': os.environ['CASHOCLOCK_DB_NAME'],
    'USER': os.environ['CASHOCLOCK_DB_USER'],
    'PASSWORD': os.environ['CASHOCLOCK_DB_PASS'],
    'HOST': os.environ['CASHOCLOCK_DB_HOST'],
  }
}

CACHES = {
  'default': {
    'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    # 'LOCATION': 'unique-snowflake',
  }
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-US'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = 'static'


# Email settings

EMAIL_HOST = ''
EMAIL_PORT = 587
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_USE_TLS = True
EMAIL_TIMEOUT = 10
DEFAULT_FROM_EMAIL = 'Gabriel Hora <gabrielhora@gmail.com>'
